### ISSUE TITLE
Joint spectrums for computing efficiencies aren't correct

### ISSUE THREAD

**Issue by kshalm** [kshalm/spdcalc#3]
http://wellcaffeinated.net/spdcalc-ui/#/?panels=W3sidHlwZSI6ImpzaSIsInNldHRpbmdzIjp7ImVuYWJsZUxvZ1NjYWxlIjpmYWxzZSwiYXV0b1VwZGF0ZSI6dHJ1ZX19LMlFaGVyYWxkaW5nLXYtd3PPUGNvbWJpbmVkSlNJ0VV4YXhpxSVtaW4iOsVkIiwibWF4IjoxMzAsInN0ZXBzIjoxMH0s5ACqUmVzb2x1dGlvbiI6xB%2F8AJRQYW5lbExvYWRlcu4Akd8lyCVd&cfg=eyJhdXRvQ2FsY1RoZXRhIjp0cnVlLMkVUGVyaW9kaWNQb2xpbmfQHkludGVncmF0aW9uTGltaXRzyCFzcGRDb25maWciOnsiY3J5c3RhbCI6IktUUCIsInBtX3R5cGUiOiJUeXBlMl9lX2VvIizIJ1905gCIOTDKE3BoaSI6yxB0ZW1wZXJhdHVyZSI6MjAsImZpYmVyX2NvdXDsAKdzaWduYWxfd2F2ZWxlbmd0aCI6MTU1MMkZx2rKEchoxw9iYW5kd2lkxTjLTmlzdCI6MTAwLCJpZGxlctNgxhjKX8YQxV4xOMkQzl%2FITMpecOcBfF9w5QF9X2VuYWJsZWToAN7oAQ3IezYwxTV1bXDtAJI3NzQuMscYy3IwyRXHczLJPnNwZWN0cnVtX3RocmVzaG9sZMQvMO8BA19wb3Np5AH6IjotMTczxCE5NTI1MDY1NjYzMu0A0M0rNjUxLjk2ODUwMTEwMjQ4Mywi5wDf5gDvIjo0Ni40MDI2Mjc0MjE0MjUyNywiYXBvZGl65QJo6gEGZmFsc%2BQCjMscZndobSI6NDUwMDB9LCJp6gKe6gKNc2l6ZSI6NOQA7WxzX21pbuQBtDQ2LjAxNTMyNzQ1MzYxMjjGHGF4xBw1My45ODQ2NzI1NDYzODc0LCJsack4Mi44NTUzMjM4Mzc5MzPHHMc4MC43OTIwNDA0NTI4Njg4fX0%3D

The signal/idler/coincidence spectrums aren't correct. They should be symmetric and closer to:

http://spdcalc.org/#lambda_p=%2B7.74e-7&lambda_s=%2B0.0000015500000000000002&lambda_i=%2B0.000001546005154639175&type=~Type%202%3A%20%20%20e%20-%3E%20e%20%2B%20o&theta=%2B1.5707963267948966&phi=%2B0&theta_s=%2B0&theta_i=%2B0&theta_s_e=%2B0&theta_i_e=%2B0&phi_s=%2B0&phi_i=%2B3.141592653589793&L=%2B0.006&W=%2B0.00019999999999999998&p_bw=%2B2.0000000000000003e-10&walkoff_p=%2B0&W_sx=%2B0.00009999999999999999&W_sy=%2B0.00009999999999999999&W_ix=%2B0.00009999999999999999&W_iy=%2B0.00009999999999999999&phase=!false&brute_force=!false&brute_dim=%2B50&autocalctheta=!false&autocalcpp=!true&poling_period=%2B0.0000463733039836472&poling_sign=%2B-1&calc_apodization=!false&apodization=%2B31&apodization_FWHM=%2B0.0015999999999999999&use_guassian_approx=!false&crystal=~KTP-3&temp=%2B20&enable_pp=!true&calcfibercoupling=!true&singles=!false&autocalfocus=!true&z0s=%2B-0.0016909201365961054&deff=%2B1e-12&Pav=%2B0.001

**Comment by wellcaffeinated** [comment]
I believe this particular bug is fixed
